from turtle import Turtle, Screen
t = Turtle()
s = Screen()
s.title(titlestring='Adobe Logo')
s.bgcolor('red')
t.color('white')
t.speed('slowest')
t.ht()
t.pu()
t.goto(x=-100, y=0)
t.pd()
t.begin_fill()
t.goto(x=-100, y=200)
t.goto(x=-30, y=200)
t.goto(x=-100, y=0)
t.end_fill()
t.pu()
t.goto(x=100, y=0)
t.pd()
t.begin_fill()
t.goto(x=100, y=200)
t.goto(x=30, y=200)
t.goto(x=100, y=0)
t.end_fill()
t.pu()
t.goto(x=60, y=0)
t.pd()
t.begin_fill()
t.goto(x=0, y=140)
t.goto(x=-40, y=40)
t.goto(x=10, y=40)
t.goto(x=30, y=0)
t.goto(x=60, y=0)
t.end_fill()
t.pu()
t.goto(0, -100)
t.write('Adobe', move=False, align='center', font=("myriad", 50, 'bold'))
s.exitonclick()
